name: Docker Image CI

on:
  schedule:
    - cron: 12 4 * * *
  push:
    branches:
      - main
      - "5.7"
      - "5.8"
      - "5.9"
jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - main
          - "5.8"
          - "5.9"

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push the Docker image
      run: |
        docker build . --file Dockerfile --tag getshifter/wp-languages:${{ matrix.branch }}
        docker push getshifter/wp-languages:${{ matrix.branch }}
