name: Docker Image CI

on:
  push:
    branches:
      - main
      - "5.6"
      - "5.7"
      - "5.8"
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set branch name
      run: echo "GH_BRANCHNAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push the Docker image
      run: |
        docker build . --file Dockerfile --tag getshifter/wp-languages:${GH_BRANCHNAME}
        docker push getshifter/wp-languages:${GH_BRANCHNAME}
